### ISSUE TITLE
Security with this adapter, and parse.js absence.

### ISSUE THREAD

**Issue by QuantumInformation** [clintjhill/ember-parse-adapter#74]
I've been looking through the code and cannot see the parse library loaded from eg:

    <script src="//www.parsecdn.com/js/parse-1.4.2.min.js"></script>

How do we actually communicate with parse without this lib?

Also I am wondering how secure user data is in our applications, how do we inforce it with this adaptor. I only want the data held in parse to be shown to the relevant parse user once the log in.

**Comment by oriSomething** [comment]
currently this project doesn't use the `Parse SDK`, it communicate with the server directly.
i'm not sure about future plans, but i can't say the `Parse SDK` is secure enough, because the session token is saved on the `localStorage` which is not secure at all if you're using third party library.
maybe enabling option of how session is saved locally if at all can be a nice addition to this library.

**Comment by QuantumInformation** [comment]
I've not used localStorage much, can you expound of the use case of "is not secure at all if you're using third party library"? 

How do we restrict our ember apps to only use the login service when you don't have a session token, and only after we get the  session token  can users do things on the app to access other tabele on parse?

**Comment by oriSomething** [comment]
1. you can't restrict `localStorage`. so if you're using third party script it can access all the data in `localStorage`, also the session token of current user when `Parse SDK` is used. here `Parse SDK` there is no use of `Parse SDK`, and so no use of `localStorage`. but because the way `Parse` works you can't really protect `session token`. only if user needs to login every time application loaded as what happens now (as last time i checked) in this project.
2. don't think this question related to this project. i think what you're looking for is `class permissions` / `ACL` in Parse docs

**Comment by QuantumInformation** [comment]
The adaptor doesn't persist to local storage, or anything else for that matter. So perhaps can't link users to object they save I think or work with ACL's. I'm still learning how parse works.

**Comment by QuantumInformation** [comment]
Use this with ember simple auth. Appears to be what we need.
